version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: task

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: passwd
      MARIADB_DATABASE: user

  tracing:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
    ports:
      - 9411:9411 

  # server:
  #   build: server
  #   environment:
  #     - PROTO_FILE=proto/task/v1beta/task.proto
  #     - MONGO_URL=mongodb://root:task@mongo
  #     - insecure=true
  #   ports:
  #     - 4000:4000

  # front:
  #   build: front
  #   environment:
  #     - SERVER=server:4000
  #   ports:
  #     - 3000:3000