version: '3.8'

services:
  mariadb:
    extends:
      file: ./compose/compose.db.yml
      service: mariadb

  mongo:
    extends:
      file: ./compose/compose.db.yml
      service: mongo

  auth-api:
    extends:
      file: ./compose/compose.local.yml
      service: auth-api

  user-api:
    extends:
      file: ./compose/compose.published.yml
      service: user-api
    
networks:
  default:
    external: true
    name: grpc-task-manager_default

  
