version: '3.8'

services:
  mariadb:
    extends:
      file: ./compose/compose.db.yml
      service: mariadb

  mongo:
    extends:
      file: ./compose/compose.db.yml
      service: mongo

  tracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
      
  # auth-api:
  #   extends:
  #     file: ./compose/compose.local.yml
  #     service: auth-api

  # user-api:
  #   extends:
  #     file: ./compose/compose.published.yml
  #     service: user-api

networks:
  default:
    external: true
    name: grpc-task-manager_default
