version: '3.8'

services:
  mariadb:
    extends:
      file: ./compose/compose.db.yml
      service: mariadb

  mongo:
    extends:
      file: ./compose/compose.db.yml
      service: mongo

  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686

  front: 
    image: front
    volumes:
      - ./local/certs:/certs
    environment:
      - ROOT_CERT=/certs/rootCA.pem
      - FRONT_KEY=/certs/front-key.pem
      - FRONT_CERT=/certs/front.pem
      - secure=true
      - TASK_API_URL=task-api:4000
      - AUTH_API_URL=auth-api:4000
      - USER_API_URL=user-api:4000
    ports:
      - 3000:3000

  auth-api:
    extends:
      file: ./compose/compose.published.yml
      service: auth-api

  user-api:
    extends:
      file: ./compose/compose.published.yml
      service: user-api

  task-api:
    extends:
      file: ./compose/compose.published.yml
      service: task-api

networks:
  default:
    external: true
    name: grpc-task-manager_default
