name: Update generated stubs

on:
  push:
    branches:
      - main
    paths:
      - "proto/**.proto"
      - ".github/workflows/proto.yml"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0
      # Installs latest

      - uses: bufbuild/buf-setup-action@v1.12.0
      - run: |
          cd proto
          buf generate

      - name: Update front stubs
        run: |
          rm -rf ./front/src/lib/stubs
          cp -r ./proto/gen ./front/src/lib/stubs

      - name: Update server stubs and proto
        run: |
          rm -rf ./server/src/proto
          rm -rf ./server/src/stubs
          buf export buf.build/bneiconseil/taskmanagerapi -o ./server/src/proto
          cp -r ./proto/gen ./server/src/stubs

      - name: Commit stubs
        run: |
          git config --local user.email "mohammadamine.banaei@gmail.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "feat(stubs): updated stubs"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
